ALTER TABLE books MODIFY COLUMN price DECIMAL(10,2);
ALTER TABLE orders MODIFY COLUMN total_price DECIMAL(10,2);
ALTER TABLE order_item MODIFY COLUMN item_price DECIMAL(10,2);
ALTER TABLE order_item MODIFY COLUMN total_price DECIMAL(10,2);
